## Matrices

In [8]:
import numpy as np

In [9]:
a = np.matrix([[1,4,7],[2,5,8],[3,6,9]])
a

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [10]:
b = np.matrix([[1,-1,2],[2,-1,2],[3,-3,0]])
b

matrix([[ 1, -1,  2],
        [ 2, -1,  2],
        [ 3, -3,  0]])

In [16]:
a/b

C:\Users\jonac\AppData\Local\Temp\ipykernel_5208\1348051284.py:1: RuntimeWarning: divide by zero encountered in divide
  a/b


matrix([[ 1. , -4. ,  3.5],
        [ 1. , -5. ,  4. ],
        [ 1. , -2. ,  inf]])